gravity: 9.8

# color: "#XXXXXX" or "default" or "random"
color: "default"

# 1 -> 10
num_pidgets: 0

# Checks for images in /usr/share/local/pidget/ by default
# image_path: "/my/image/dir/"

# Currently only supports three images
images:
  - frog-1.png
  - frog-2.png
  - frog-3.png
